#import <Foundation/Foundation.h>
#import "SWGInput1.h"
#import "SWGInput2.h"
#import "SWGInput3.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGConvertWebApi: NSObject <SWGApi>

extern NSString* kSWGConvertWebApiErrorDomain;
extern NSInteger kSWGConvertWebApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Convert HTML string to PDF
/// Fully renders a website and returns a PDF of the HTML.  Javascript, HTML5, CSS and other advanced features are all supported.
///
/// @param input HTML to PDF request parameters
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) convertWebHtmlToPdfWithInput: (SWGInput3*) input
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Convert a URL to PDF
/// Fully renders a website and returns a PDF of the full page.  Javascript, HTML5, CSS and other advanced features are all supported.
///
/// @param input URL to PDF request parameters
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) convertWebUrlToPdfWithInput: (SWGInput2*) input
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Take screenshot of URL
/// Fully renders a website and returns a PNG screenshot of the full page image.  Javascript, HTML5, CSS and other advanced features are all supported.
///
/// @param input Screenshot request parameters
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) convertWebUrlToScreenshotWithInput: (SWGInput1*) input
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;



@end
