#import <Foundation/Foundation.h>
#import "SWGInlineResponse20018.h"
#import "SWGValue.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGConvertTemplateApi: NSObject <SWGApi>

extern NSString* kSWGConvertTemplateApiErrorDomain;
extern NSInteger kSWGConvertTemplateApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Apply HTML template
/// Apply operations to fill in an HTML template, generating a final HTML result
///
/// @param value Operations to apply to template
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20018*
-(NSURLSessionTask*) convertTemplateApplyHtmlTemplateWithValue: (SWGValue*) value
    completionHandler: (void (^)(SWGInlineResponse20018* output, NSError* error)) handler;



@end
