#import <Foundation/Foundation.h>
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGConvertDocumentApi: NSObject <SWGApi>

extern NSString* kSWGConvertDocumentApiErrorDomain;
extern NSInteger kSWGConvertDocumentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Convert Document to PDF
/// Automatically detect file type and convert it to PDF.
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) convertDocumentAutodetectToPdfWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Word DOCX to PDF
/// Convert Office Word Documents (docx) to standard PDF
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) convertDocumentDocxToPdfWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// PowerPoint PPTX to PDF
/// Convert Office PowerPoint Documents (pptx) to standard PDF
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) convertDocumentPptxToPdfWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Excel XLSX to CSV
/// Convert Office Excel Workbooks (xlsx) to standard Comma-Separated Values (CSV) format.
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) convertDocumentXlsxToCsvWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Excel XLSX to PDF
/// Convert Office Excel Workbooks (xlsx) to standard PDF.  Converts all worksheets in the workbook to PDF.
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) convertDocumentXlsxToPdfWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;



@end
