#import <Foundation/Foundation.h>
#import "SWGInlineResponse200.h"
#import "SWGInlineResponse2001.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGDomainApi: NSObject <SWGApi>

extern NSString* kSWGDomainApiErrorDomain;
extern NSInteger kSWGDomainApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Validate a domain name
/// Check whether a domain name is valid or not.  API performs a live validation by contacting DNS services to validate the existence of the domain name.
///
/// @param domain Domain name to check, for example \&quot;cloudmersive.com\&quot;
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse200*
-(NSURLSessionTask*) domainCheckWithDomain: (NSString*) domain
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// Get WHOIS information for a domain
/// Validate whether a domain name exists, and also return the full WHOIS record for that domain name.  WHOIS records include all the registration details of the domain name, such as information about the domain's owners.
///
/// @param domain Domain name to check, for example \&quot;cloudmersive.com\&quot;
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2001*
-(NSURLSessionTask*) domainPostWithDomain: (NSString*) domain
    completionHandler: (void (^)(SWGInlineResponse2001* output, NSError* error)) handler;



@end
