#import <Foundation/Foundation.h>
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGExtractEntitiesStringApi: NSObject <SWGApi>

extern NSString* kSWGExtractEntitiesStringApiErrorDomain;
extern NSInteger kSWGExtractEntitiesStringApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Extract entities from string
/// Extract the named entitites from an input string.
///
/// @param value Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) extractEntitiesStringPostWithValue: (NSString*) value
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
