#import <Foundation/Foundation.h>
#import "SWGInlineResponse20015.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGFaceApi: NSObject <SWGApi>

extern NSString* kSWGFaceApiErrorDomain;
extern NSInteger kSWGFaceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Crop image to face (square)
/// Crop an image to the face (rectangular crop).  If there is more than one face present, choose the first one.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) faceCropFirstWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Crop image to face (round)
/// Crop an image to the face (circular/round crop).  If there is more than one face present, choose the first one.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSURL*
-(NSURLSessionTask*) faceCropFirstRoundWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// Find faces in an image
/// Locate the positions of all faces in an image
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20015*
-(NSURLSessionTask*) faceLocateWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(SWGInlineResponse20015* output, NSError* error)) handler;



@end
