#import <Foundation/Foundation.h>
#import "SWGInlineResponse2005.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGIPAddressApi: NSObject <SWGApi>

extern NSString* kSWGIPAddressApiErrorDomain;
extern NSInteger kSWGIPAddressApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Geolocate an IP address
/// Identify an IP address Country, State/Provence, City, Zip/Postal Code, etc.  Useful for security and UX applications.
///
/// @param value IP address to geolocate, e.g. \&quot;55.55.55.55\&quot;
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2005*
-(NSURLSessionTask*) iPAddressPostWithValue: (NSString*) value
    completionHandler: (void (^)(SWGInlineResponse2005* output, NSError* error)) handler;



@end
