#import <Foundation/Foundation.h>
#import "SWGInlineResponse20013.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGImageOcrApi: NSObject <SWGApi>

extern NSString* kSWGImageOcrApiErrorDomain;
extern NSInteger kSWGImageOcrApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Converts an uploaded image in common formats such as JPEG, PNG into text via Optical Character Recognition.
/// 
///
/// @param imageFile Image file to perform OCR on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20013*
-(NSURLSessionTask*) imageOcrPostWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(SWGInlineResponse20013* output, NSError* error)) handler;



@end
