#import <Foundation/Foundation.h>
#import "SWGInlineResponse2007.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGLanguageDetectionApi: NSObject <SWGApi>

extern NSString* kSWGLanguageDetectionApiErrorDomain;
extern NSInteger kSWGLanguageDetectionApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Detect language of text
/// Automatically determine which language a text string is written in.  Supports Danish (DAN), German (DEU), English (ENG), French (FRA), Italian (ITA), Japanese (JPN), Korean (KOR), Dutch (NLD), Norwegian (NOR), Portuguese (POR), Russian (RUS), Spanish (SPA), Swedish (SWE), Chinese (ZHO).
///
/// @param textToDetect Text to detect language of
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2007*
-(NSURLSessionTask*) languageDetectionPostWithTextToDetect: (NSString*) textToDetect
    completionHandler: (void (^)(SWGInlineResponse2007* output, NSError* error)) handler;



@end
