#import <Foundation/Foundation.h>
#import "SWGInlineResponse20016.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGNsfwApi: NSObject <SWGApi>

extern NSString* kSWGNsfwApiErrorDomain;
extern NSInteger kSWGNsfwApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// NSFW image classifier
/// Classify an image into Not Safe For Work (NSFW)/Porn/Racy content and Safe Content.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20016*
-(NSURLSessionTask*) nsfwClassifyWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(SWGInlineResponse20016* output, NSError* error)) handler;



@end
