#import <Foundation/Foundation.h>
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGPosTaggerStringApi: NSObject <SWGApi>

extern NSString* kSWGPosTaggerStringApiErrorDomain;
extern NSInteger kSWGPosTaggerStringApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Part-of-speech tag a string
/// Perform a part-of-speech (POS) tagging on the input string.
///
/// @param input Input string
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) posTaggerStringPostWithInput: (NSString*) input
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
