#import <Foundation/Foundation.h>
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGResizeApi: NSObject <SWGApi>

extern NSString* kSWGResizeApiErrorDomain;
extern NSInteger kSWGResizeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Resize an image with parameters
/// Resize an image to a maximum width and maximum height, while preserving the image's original aspect ratio
///
/// @param maxWidth Maximum width of the output image - final image will be as large as possible while less than or equial to this width
/// @param maxHeight Maximum height of the output image - final image will be as large as possible while less than or equial to this height
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) resizePostWithMaxWidth: (NSNumber*) maxWidth
    maxHeight: (NSNumber*) maxHeight
    imageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
