#import <Foundation/Foundation.h>
#import "SWGInlineResponse20017.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGRecognizeApi: NSObject <SWGApi>

extern NSString* kSWGRecognizeApiErrorDomain;
extern NSInteger kSWGRecognizeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Describe an image in natural language
/// Generate an English language text description of the image as a sentence.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20017*
-(NSURLSessionTask*) recognizeDescribeWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(SWGInlineResponse20017* output, NSError* error)) handler;



@end
