#import <Foundation/Foundation.h>
#import "SWGInlineResponse20010.h"
#import "SWGInlineResponse20011.h"
#import "SWGInlineResponse2009.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGSpellCheckApi: NSObject <SWGApi>

extern NSString* kSWGSpellCheckApiErrorDomain;
extern NSInteger kSWGSpellCheckApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Spell check word
/// Spell check a word as JSON
///
/// @param value Input sentence
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20010*
-(NSURLSessionTask*) spellCheckCheckJsonWithValue: (NSString*) value
    completionHandler: (void (^)(SWGInlineResponse20010* output, NSError* error)) handler;


/// Check if sentence is spelled correctly
/// Checks whether the sentence is spelled correctly and returns the result as JSON
///
/// @param value Input sentence
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2009*
-(NSURLSessionTask*) spellCheckCheckSentenceJsonWithValue: (NSString*) value
    completionHandler: (void (^)(SWGInlineResponse2009* output, NSError* error)) handler;


/// Spell check a sentence
/// Check if a sentence is spelled correctly
///
/// @param value Input sentence word
/// 
///  code:200 message:"OK"
///
/// @return NSNumber*
-(NSURLSessionTask*) spellCheckCheckSentenceStringWithValue: (NSString*) value
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;


/// Find spelling corrections
/// Find the spelling corrections for a word
///
/// @param value Input word
/// 
///  code:200 message:"OK"
///
/// @return NSString*
-(NSURLSessionTask*) spellCheckCorrectWithValue: (NSString*) value
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// Find spelling corrections
/// Find spelling correction suggestions and return result as JSON
///
/// @param value Input string
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20011*
-(NSURLSessionTask*) spellCheckCorrectJsonWithValue: (NSString*) value
    completionHandler: (void (^)(SWGInlineResponse20011* output, NSError* error)) handler;


/// Spell check a word
/// Check if a word is spelled correctly
///
/// @param value Input string word
/// 
///  code:200 message:"OK"
///
/// @return NSNumber*
-(NSURLSessionTask*) spellCheckPostWithValue: (NSString*) value
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;



@end
