#import <Foundation/Foundation.h>
#import "SWGInlineResponse2006.h"
#import "SWGInput.h"
#import "SWGApi.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGVatApi: NSObject <SWGApi>

extern NSString* kSWGVatApiErrorDomain;
extern NSInteger kSWGVatApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Lookup a VAT code
/// Checks if a VAT code is valid, and if it is, returns more information about it
///
/// @param input Input VAT code
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2006*
-(NSURLSessionTask*) vatVatLookupWithInput: (SWGInput*) input
    completionHandler: (void (^)(SWGInlineResponse2006* output, NSError* error)) handler;



@end
