#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGConverttemplatehtmlapplyOperations
@end

@interface SWGConverttemplatehtmlapplyOperations : SWGObject


@property(nonatomic) NSNumber* action;

@property(nonatomic) NSString* matchAgsint;

@property(nonatomic) NSString* replaceWith;

@end
