#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse2006
@end

@interface SWGInlineResponse2006 : SWGObject


@property(nonatomic) NSString* countryCode;

@property(nonatomic) NSString* vatNumber;

@property(nonatomic) NSNumber* isValid;

@property(nonatomic) NSString* businessName;

@property(nonatomic) NSString* businessAddress;

@end
