#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse20012Words.h"
@protocol SWGInlineResponse20012Words;
@class SWGInlineResponse20012Words;



@protocol SWGInlineResponse20012
@end

@interface SWGInlineResponse20012 : SWGObject

/* Array of words [optional]
 */
@property(nonatomic) NSArray<SWGInlineResponse20012Words>* words;

@end
