#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse2002
@end

@interface SWGInlineResponse2002 : SWGObject

/* True if the email address is syntactically valid, false if it is not [optional]
 */
@property(nonatomic) NSNumber* validAddress;

@end
