#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse2004
@end

@interface SWGInlineResponse2004 : SWGObject

/* True if the email address is valid, false otherwise [optional]
 */
@property(nonatomic) NSNumber* validAddress;
/* Email server connected to for verification [optional]
 */
@property(nonatomic) NSString* mailServerUsedForValidation;

@end
