#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse20019FoundViruses
@end

@interface SWGInlineResponse20019FoundViruses : SWGObject

/* Name of the file containing the virus [optional]
 */
@property(nonatomic) NSString* fileName;
/* Name of the virus that was found [optional]
 */
@property(nonatomic) NSString* virusName;

@end
