#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse2005
@end

@interface SWGInlineResponse2005 : SWGObject

/* Two-letter country code of IP address [optional]
 */
@property(nonatomic) NSString* countryCode;
/* Country name of IP address [optional]
 */
@property(nonatomic) NSString* countryName;
/* City of IP address [optional]
 */
@property(nonatomic) NSString* city;
/* State/region code of IP address [optional]
 */
@property(nonatomic) NSString* regionCode;
/* State/region of IP address [optional]
 */
@property(nonatomic) NSString* regionName;
/* Zip or postal code of IP address [optional]
 */
@property(nonatomic) NSString* zipCode;
/* Timezone of IP address [optional]
 */
@property(nonatomic) NSString* timezoneStandardName;
/* Latitude of IP address [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* Longitude of IP address [optional]
 */
@property(nonatomic) NSNumber* longitude;

@end
