#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse2008TaggedSentences.h"
@protocol SWGInlineResponse2008TaggedSentences;
@class SWGInlineResponse2008TaggedSentences;



@protocol SWGInlineResponse2008
@end

@interface SWGInlineResponse2008 : SWGObject

/* Sentences in the string [optional]
 */
@property(nonatomic) NSArray<SWGInlineResponse2008TaggedSentences>* taggedSentences;

@end
