#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse20017BestOutcome
@end

@interface SWGInlineResponse20017BestOutcome : SWGObject

/* Scores closer to 1 are better than scores closer to 0 [optional]
 */
@property(nonatomic) NSNumber* confidenceScore;
/* English language description of the image [optional]
 */
@property(nonatomic) NSString* _description;

@end
