#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse2009Words.h"
@protocol SWGInlineResponse2009Words;
@class SWGInlineResponse2009Words;



@protocol SWGInlineResponse2009
@end

@interface SWGInlineResponse2009 : SWGObject

/* Number of incorrect words [optional]
 */
@property(nonatomic) NSNumber* incorrectCount;
/* Words in the sentence, both correct and incorrect [optional]
 */
@property(nonatomic) NSArray<SWGInlineResponse2009Words>* words;

@end
