#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse20012Words
@end

@interface SWGInlineResponse20012Words : SWGObject

/* Word as a string [optional]
 */
@property(nonatomic) NSString* word;
/* Zero-based index of the word; first word has index 0, second word has index 1 and so on [optional]
 */
@property(nonatomic) NSNumber* wordIndex;
/* Zero-based character offset at which the word begins in the input string [optional]
 */
@property(nonatomic) NSNumber* startPosition;
/* Zero-based character offset at which the word ends in the input string [optional]
 */
@property(nonatomic) NSNumber* endPosition;

@end
