#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse2009Word.h"
@protocol SWGInlineResponse2009Word;
@class SWGInlineResponse2009Word;



@protocol SWGInlineResponse2009Words
@end

@interface SWGInlineResponse2009Words : SWGObject


@property(nonatomic) SWGInlineResponse2009Word* word;
/* True if the word is spelled correctly, false otherwise [optional]
 */
@property(nonatomic) NSNumber* correct;
/* Suggested spelling improvements [optional]
 */
@property(nonatomic) NSArray<NSString*>* suggestions;

@end
