#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse2008Words.h"
@protocol SWGInlineResponse2008Words;
@class SWGInlineResponse2008Words;



@protocol SWGInlineResponse2008TaggedSentences
@end

@interface SWGInlineResponse2008TaggedSentences : SWGObject

/* Words in the sentence [optional]
 */
@property(nonatomic) NSArray<SWGInlineResponse2008Words>* words;

@end
