#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse20014Matches.h"
@protocol SWGInlineResponse20014Matches;
@class SWGInlineResponse20014Matches;



@protocol SWGInlineResponse20014
@end

@interface SWGInlineResponse20014 : SWGObject


@property(nonatomic) NSNumber* successful;

@property(nonatomic) NSArray<SWGInlineResponse20014Matches>* matches;

@end
