#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse2001
@end

@interface SWGInlineResponse2001 : SWGObject

/* True if the domain is valid, false if it is not [optional]
 */
@property(nonatomic) NSNumber* validDomain;
/* Server used to lookup WHOIS information (may change based on lookup). [optional]
 */
@property(nonatomic) NSString* whoisServer;
/* WHOIS raw text record [optional]
 */
@property(nonatomic) NSString* rawTextRecord;
/* Creation date for the record [optional]
 */
@property(nonatomic) NSDate* createdDt;

@end
