#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse20015Faces
@end

@interface SWGInlineResponse20015Faces : SWGObject

/* X coordinate of the left side of the face [optional]
 */
@property(nonatomic) NSNumber* leftX;
/* Y coordinate of the top side of the face [optional]
 */
@property(nonatomic) NSNumber* topY;
/* X coordinate of the right side of the face [optional]
 */
@property(nonatomic) NSNumber* rightX;
/* Y coordinate of the bottom side of the face [optional]
 */
@property(nonatomic) NSNumber* bottomY;

@end
