#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse20011
@end

@interface SWGInlineResponse20011 : SWGObject

/* True if the word is spelled correctly, false otherwise [optional]
 */
@property(nonatomic) NSNumber* correct;
/* Suggested spelling corrections [optional]
 */
@property(nonatomic) NSArray<NSString*>* suggestions;

@end
