#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse20019FoundViruses.h"
@protocol SWGInlineResponse20019FoundViruses;
@class SWGInlineResponse20019FoundViruses;



@protocol SWGInlineResponse20019
@end

@interface SWGInlineResponse20019 : SWGObject

/* True if the scan contained no viruses, false otherwise [optional]
 */
@property(nonatomic) NSNumber* cleanResult;
/* Array of viruses found, if any [optional]
 */
@property(nonatomic) NSArray<SWGInlineResponse20019FoundViruses>* foundViruses;

@end
