#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGInlineResponse2007
@end

@interface SWGInlineResponse2007 : SWGObject

/* True if the language detection operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* ISO 639 three letter language code [optional]
 */
@property(nonatomic) NSString* detectedLanguageThreeLetterCode;
/* The full name (in English) of the detected language [optional]
 */
@property(nonatomic) NSString* detectedLanguageFullName;

@end
