#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Cloudmersive
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse20015Faces.h"
@protocol SWGInlineResponse20015Faces;
@class SWGInlineResponse20015Faces;



@protocol SWGInlineResponse20015
@end

@interface SWGInlineResponse20015 : SWGObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Array of faces found in the image [optional]
 */
@property(nonatomic) NSArray<SWGInlineResponse20015Faces>* faces;
/* Number of faces found in the image [optional]
 */
@property(nonatomic) NSNumber* faceCount;

@end
